title: Siyan Zhu
# logo: /assets/img/me4.jpg
description: Game Engine Dev
# description: Master's student at Beihang University
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
url: "https://okifuz.github.io"

exclude:
  - docs
